### ISSUE TITLE
Crashes on iOS 14

### ISSUE THREAD

**Issue by Eraminel01** [Lessica/Reveil#1]
Crash log:
Date: 1/1/24, 4:36 AM
Process: Reveil
Bundle id: com.reveil.app
Device: iPhone SE (1st generation), iOS 14.4.1
Bundle version: 1.2

Exception type: EXC_SOFTWARE (SIGABRT)
Exception subtype: EXC_UNIX_ABORT
Exception codes: 0x0000000000010002, 0x0000000000000000
Culprit: Unknown
Termination Reason: Symbol not found: _kIOMainPortDefault
  Referenced from: /private/var/containers/Bundle/Application/9CB07C9E-444F-425C-861D-BC65AA05D466/Reveil.app/Frameworks/library_stub.framework/library_stub (which was built for iOS 15.0)
  Expected in: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit

**Comment by dlevi309** [comment]
It’s officially supported on devices running 15.0 and up but if this is the *only* compatibility issue, a change could be made to support iOS 14 devices by redirecting `_kIOMainPortDefault` symbol to `_kIOMasterPortDefault` (the symbol was renamed on iOS 15)

**Comment by Lessica** [comment]
Reveil is designed to work on iOS 15 and above.
