### ISSUE TITLE
关于Reveil语言适配问题

### ISSUE THREAD

**Issue by CaslenZ** [Lessica/Reveil#10]
我的iOS系统是繁体中文语言的，我有留意到程序是有简体中文版本的，可能程序识别到我的系统语言就自动切换到英文了。但是我们这边虽然习惯用繁中但是我们不普及英语，所以希望可以有语言选择的功能（或者开发繁中）。感谢！

**Comment by Lessica** [comment]
欢迎贡献翻译，请勿使用简繁机转。参照：https://github.com/Lessica/Reveil/blob/main/Reveil/zh-Hans.lproj/Localizable.strings

**Comment by CaslenZ** [comment]
已将文件发送到您邮箱，请查收。

**Comment by Lessica** [comment]
已收到，预计今天晚些时候检视合入。
