### ISSUE TITLE
Build Archive doesn't work anymore

### ISSUE THREAD

**Issue by k3v1nwrld** [Lessica/Reveil#14]
Tried forking the repo and running Build Archive, but it gives an error about the project being damaged and unable to be opened. I've got a MacOS vm but have no idea how to build it manually. Thanks

**Comment by Lessica** [comment]
I’m not going to teach you how to build this project because no additional step is required. Just open Xcode and click build, that’s all. If you have difficulty with that, you need to learn how to use Xcode.

**Comment by k3v1nwrld** [comment]
Looks like my vm supports up to Xcode 14 and not 15. Is there any way to set up automatic updates for the .tipa or is that a nono??

**Comment by Lessica** [comment]
Use the `.tipa` from the Release page. Reveil will not be frequently updated.
