### ISSUE TITLE
“应用程序分发配置文件被篡改”  

### ISSUE THREAD

**Issue by VINCENTCHEN94** [Lessica/Reveil#2]
![WechatIMG121413](https://github.com/Lessica/Reveil/assets/35206112/089f462f-7260-41bf-86ff-8f6e48042da3)
iPhone12PM ios16.1.1

**Comment by Lessica** [comment]
通过巨魔安装的版本，实质上篡改了 App 权利表、代码签名、App 分发配置文件等。这是正常现象。如果越狱，标红检查项只会更多。

**Comment by VINCENTCHEN94** [comment]
好的 感谢
