### ISSUE TITLE
What does it means and how to fix it

### ISSUE THREAD

**Issue by sjtuwater** [Lessica/Reveil#3]

**Comment by sjtuwater** [comment]
![973a627d2b021e3b622da777f6a9156](https://github.com/Lessica/Reveil/assets/61745138/69d9f7d0-e392-4eea-bc97-e992facc0baa)
it show something has changed， but i install trollstore today ，and install reveil just now，and it show the problem here，I have no any authority to modify any file before install TrollStore 
So, anybody get the same situation ?

**Comment by Lessica** [comment]
巨魔本身的实现就是在突破安全限制，并非误报。
